server:
  port: 8188
  servlet:
    context-path: /pintekoMarket

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: berbedos31
    driver-class-name: org.postgresql.Driver
  jpa:
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQL10Dialect
      show-sql: true
  flyway:
      baseline-on-migrate: true

jwt:
  secret: pintekoanastasiahardbuttonbutterfly
  lifetime: 3600000
#eureka:
#  instance:
#    hostname: localhost
#  client:
#    serviceUrl:
#      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
#      fetchRegistry: false