server:
  port: 8189
  servlet:
    context-path: /pinteko-market-book
utils:
  cart:
    prefix: SPRING_WEB_
integrations:
  cart-service:
    url: http://localhost:5555/cart
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: berbedos31
    driver-class-name: org.postgresql.Driver
  jpa:
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQL10Dialect
      show-sql: true
  flyway:
      baseline-on-migrate: true